config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # analysis_categories
  root :to => 'analysis_categories#select_categories', via: [:get, :post]
  match 'get_feature_samples', to: 'analysis_categories#get_feature_samples', via: [:get, :post]
  match 'feature_samples_sendfile', to: 'analysis_categories#send_feature_samples_file', via: [:get, :post]

  # pages
  match "pages/geneselection", via: 'get'
  match 'gene_selection', to: 'pages#gene_selection', via: [:get, :post]
  match 'gene_selection_sendfile', to: 'pages#send_gene_selection_file', via: [:get, :post]

  match "pages/analysispipeline", to: 'pages#analysispipeline', via: 'get'
  match "pages/datainformation", to: 'pages#datainformation', via: 'get'
  match "pages/projectoverview", to: 'pages#projectoverview', via: 'get'
  match "pages/interpretation", to: 'pages#interpretation', via: 'get'
  match "pages/about", to: 'pages#about', via: 'get'

  match 'send_zip_file', to: 'pages#send_zip_file', via: [:get, :post]

  # high_level_summaries
  match 'show_summary', to: 'high_level_summaries#show_summary_table',  via: :get

  # outcome_summaries
  match 'show_outcome', to: 'outcome_summaries#show_outcome_table',  via: [:get, :post]
  match 'send_file', to: 'outcome_summaries#send_file', via: [:get, :post]
  match 'search_all_outcome_tables', to: 'outcome_summaries#search_outcome_tables', via: [:get, :post]
  match 'search_input_outcome_tables', to: 'outcome_summaries#search_outcome_tables', via: [:get, :post]
  match 'search_genes', to: 'outcome_summaries#search_genes', via: [:get, :post]

end

app/models/analysis_category.rb
class AnalysisCategory < ApplicationRecord
  
  def self.get_feature_samples_table(fn)
    file_path = CoadreadTcga::Application::config.data_file_root + ['2013-01-16', 'COADREAD', 'Matrix', fn].join('/')
    feature_samples_table_array = ApplicationController.get_table_array(file_path) if File.exists?(file_path)
    feature_samples_table_array
  end
  
  def self.get_feature_samples_metadata_table(fn)
    file_path = CoadreadTcga::Application::config.data_file_root + ['2013-01-16', 'COADREAD', 'HighLevel_Summary', fn].join("/")
    feature_samples_metadata_table_array = ApplicationController.get_table_array(file_path) if File.exists?(file_path)
    feature_samples_metadata_table_array
  end
  
end

app/controllers/analysis_categories_controller.rb
class AnalysisCategoriesController < ApplicationController
  
  # GET /analysis_results
  # GET /analysis_results.json
  def index
    respond_to do |format|
       format.html # index.html.erb
       format.json { render json: @analysis_results }
     end
  end
  
  def select_categories
    cancer_type    = 'COADREAD'
    data_set       = '2013-01-16'
    gene_set       = 'CancerGenes'
    mir_set        = 'AllmiR'
    hi_lev_genomic = 'Integrative'

    summary_table_array = HighLevelSummary.get_summary_table(cancer_type, data_set, gene_set, hi_lev_genomic)
    summary_table_array.shift(2) #remove the header lines
    render 'select_categories', :locals => {summary_table_array: summary_table_array, cancer_type: cancer_type, data_set: data_set, gene_set: gene_set, mir_set: mir_set, hi_lev_genomic: hi_lev_genomic}
  end
  
  def get_feature_samples
    @filename = sanitize_file_name(params[:filename])
    @metadata_filename = @filename.gsub(/\A.*_([\w-]+\.txt)\Z/, '\1' ) if !@filename.blank? #get just the feature part of filename at end

    @table_array = AnalysisCategory.get_feature_samples_table(@filename) if !@filename.blank?
    @table_array_metadata = AnalysisCategory.get_feature_samples_metadata_table(@metadata_filename)
 
    @hash_metadata = @table_array_metadata.inject(Hash.new{ |h,k| h[k]=[] }){ |h,(k,v)| h[k] << v; h } if !@table_array_metadata.blank?
      
    if @table_array.blank? || @hash_metadata.blank?
      respond_to do |format|
        format.html { 
            flash[:notice] = "Sorry, no sample data was found for #{@metadata_filename.gsub('.txt','')}"         
            redirect_to root_path
          }
        end # /respond_to
    else
      @metadata_headings = @table_array_metadata.shift;
      render 'feature_samples_table'
    end

  end
  
  def send_feature_samples_file(filename = sanitize_file_name(params[:filename]))
    table_array = AnalysisCategory.get_feature_samples_table(filename)
    csv_file = ApplicationController.to_csv(filename, table_array)
    send_data csv_file, :type => 'text/csv; charset=iso-8859-1; header=present', 
      :disposition => "attachment;filename=#{filename.gsub('.txt', '.csv')}"
  end

end

app/views/analysis_categories/_search_form.html.erb
<div class="search-box">
  <p><%= button_to "VIEW & SEARCH ALL GENES IN STUDY", search_all_outcome_tables_path, class:"", style: "width:289px;", 'data-no-turbolink' => true %></p>

<%= form_tag(search_input_outcome_tables_path, :method => "post", id: "search-form", 'data-no-turbolink' => true ) do %>            

<%
=begin %>
  <label>Select From Prominent Genes:</label>&nbsp;
     <%= select("genesearch", "genes_select", options_for_select(%w[TP53 KRAS APC], ""), 
     {:prompt => "Select Gene"}) %></p>
<%
=end %>

  <label>Enter one or more Genes separated by comma or space</label>
  <%= hidden_field_tag("input_search")%>
  <p><%= text_area_tag "genesearch[genes_text]", '', size: "38x3" %></p>
  <p><%= submit_tag "Search" %></p> 
<% end %>            
</div>

app/views/analysis_categories/feature_samples_table.html.erb
<h1>Samples information</h1>
<div style="text-align:center;">
DOWNLOAD: <%= link_to 'CSV', feature_samples_sendfile_path(filename: @filename) %>
</div>

<div class="feature_samples">
<table class="gene_selection" style="float:left;">
  <thead>
  <tr>						
  	<th class="primary_thead" colspan="<%= @table_array[0].length %>"><%= @metadata_filename.gsub('.txt','') %></th>	
  </tr>
  <tr>						
  	<th>Sample</th>
  	<th>Value</th>		
  </tr>
  </thead>
  <tbody>
  <% @table_array.each do |row| %>
  <tr>
  	<td><%= row[0] %></td>  	
    <td style="text-align:center"><%= row[1] %></td>    
  </tr>
  <% end %>
  </tbody>
</table>

<table class="gene_selection" style="float:right;">
  <thead>
  <tr>						
  	<th colspan="2" style="background-color:#f9fd7e">Meaning of Value</th>
  </tr>						

  <tr>						
  	<th style="background-color:#f9fd7e"><%= @metadata_headings[0] %></th>
  	<th style="background-color:#f9fd7e"><%= @metadata_headings[1] %></th>		
  </tr>
  </thead>
  
  <tbody>
  <% @hash_metadata.each_pair do |value, clin_params| %>
    <tr>
      <td style="text-align:center; vertical-align:top"><%= value %></td>
      <td>
      	<% clin_params.each do |cp| %>
          <%= cp %><br>
        <% end %>
      </td>
    </tr> 
  <% end %>
  </tbody>
</table>
</div>

app/views/analysis_categories/select_categories.html.erb
<h1>Systematic identification of colorectal cancer genes delineating clinical stage and metastasis</h1>

<% if flash[:notice] -%>
  <div id="notice"><strong><%= flash[:notice] %></strong></div>
<% end -%>


<table class="content-2cols" style="width:100%">
  <tr>  	 	
  	<td style="width:50%;">
  	  <p>Colorectal cancer is the third leading cause of cancer deaths in the United States.  
  	  The initial assessment of colorectal cancer involves clinical staging that takes into account the extent of primary tumor invasion (T), 
  	  determining the number of lymph nodes (N) with metastatic cancer and the identification of metastatic sites (M) in other organs.  
  	  Advanced clinical stage (III or IV) indicates metastatic cancer, either in regional lymph nodes or in distant organs.  
  	  Little is know about the identity of specific cancer genes that are associated with advanced clinical stage and metastasis.</p>

      <p>We compiled multiple genomic data types (mutations, copy number alterations, 
      	gene expression and methylation status) as well as clinical meta-data from <a href="http://cancergenome.nih.gov/‎"><strong>The Cancer Genome Atlas (TCGA)</strong></a>.   
      	Our analysis of multiple genomic features identifies a number of colorectal cancer genes associated with advanced clinical stage disease and metastasis.</p>
    </td>
    <td style="width:50%; background-color:#e7e7e7">
  	  <%= render partial: "search_form" %>    
  	</td> 
  </tr>
</table>

  <% n_status_row       = summary_table_array[0] %>
  <% cancer_type_row    = summary_table_array[1] %>
  <% clinicalstage_row  = summary_table_array[3] %>
  <% t_status_row       = summary_table_array[4] %>
  <% msi_status_row     = summary_table_array[5] %>
  <% clinicalstage_row  = summary_table_array[6] %>
   
<table class="hi-level-charts">
<tr>
  <td>
  	<div class="content-box"><h3><%= clinicalstage_row[0] %></h3><%= clinicalstage_row[2].gsub(/\A.*\//, '') %> Genes

  	  <table style="border-collapse:collapse; margin:0 auto;">
  	  	<tr>  	  	  	
  	  	  <td><%= button_to "View Genes", show_outcome_path(cancer_type: cancer_type, data_set: data_set, gene_set: gene_set, 
  	  	                                                    hi_lev_genomic: hi_lev_genomic, clinical_feature: clinicalstage_row[0]), class:"button" %></td>
          <td><%= button_to "View miR", show_outcome_path(cancer_type: cancer_type, data_set: data_set, mir_set: mir_set,
                                                            hi_lev_genomic: hi_lev_genomic, clinical_feature: clinicalstage_row[0]), class:"button" %></td>
  	  	</tr>
  	  </table>  	  	  
                                                                                                                                                      
      <%= link_to image_tag("tumorstage_2.png", height:"150px", alt:"ClinicalStage chart", title:"ClinicalStage chart"), 
          get_feature_samples_path(filename:'Y_COADREAD_2013-01-16_CancerGenes_Integrative_ClinicalStage.txt') %>
      
      <%= button_to "View Samples", get_feature_samples_path(filename:'Y_COADREAD_2013-01-16_CancerGenes_Integrative_ClinicalStage.txt'), class:"button" %>
      
  	</div>
  </td>

  <td>
  	<div class="content-box"><h3><%= t_status_row[0] %></h3><%= t_status_row[2].gsub(/\A.*\//, '') %> Genes
  		
  	  <table style="border-collapse:collapse; margin:0 auto;">
  	  	<tr>  	  	  	
  	  	  <td><%= button_to "View Genes", show_outcome_path(cancer_type: cancer_type, data_set: data_set, gene_set: gene_set,
                                                            hi_lev_genomic: hi_lev_genomic, clinical_feature: t_status_row[0]), class:"button" %></td>
  	  	  <td><%= button_to "View miR", show_outcome_path(cancer_type: cancer_type, data_set: data_set, mir_set: mir_set,
                                                            hi_lev_genomic: hi_lev_genomic, clinical_feature: t_status_row[0]), class:"button" %></td>
  	  	</tr>
  	  </table>
  	  
  	  <%= link_to image_tag("T_grade_2.png", height:"150px", alt:"T Status chart", title:"T Status chart"), 
          get_feature_samples_path(filename:'Y_COADREAD_2013-01-16_CancerGenes_Integrative_T-Status.txt') %> 
          
      <%= button_to "View Samples", get_feature_samples_path(filename:'Y_COADREAD_2013-01-16_CancerGenes_Integrative_T-Status.txt'), class:"button" %>
            	  		  	             
  	</div>
  </td>
    	  
  <td>
    <div class="content-box"><h3><%= n_status_row[0] %></h3><%= n_status_row[2].gsub(/\A.*\//, '') %> Genes
    	
      <table style="border-collapse:collapse; margin:0 auto;">
  	  	<tr>  	  	  	
  	  	  <td><%= button_to "View Genes", show_outcome_path(cancer_type: cancer_type, data_set: data_set, gene_set: gene_set,
                                                            hi_lev_genomic: hi_lev_genomic, clinical_feature: n_status_row[0]), class:"button" %> </td>
  	  	  <td><%= button_to "View miR", show_outcome_path(cancer_type: cancer_type, data_set: data_set, mir_set: mir_set,
                                                            hi_lev_genomic: hi_lev_genomic, clinical_feature: n_status_row[0]), class:"button" %></td>	  	  
  	  	</tr>
  	  </table>
    	  	  	
      <%= link_to image_tag("N_grade_2.png", height:"150px", alt:"N Status chart", title:"N Status chart"), 
          get_feature_samples_path(filename:'Y_COADREAD_2013-01-16_CancerGenes_Integrative_N-Status.txt') %> 
          
      <%= button_to "View Samples", get_feature_samples_path(filename:'Y_COADREAD_2013-01-16_CancerGenes_Integrative_N-Status.txt'), class:"button" %> 
            	        
  	</div>
  </td>
    	  
  <td>
    <div class="content-box"><h3><%= msi_status_row[0] %></h3><%= msi_status_row[2].gsub(/\A.*\//, '') %> Genes
    	
      <table style="border-collapse:collapse; margin:0 auto;">
  	  	<tr>  	  	  	
  	  	  <td><%= button_to "View Genes", show_outcome_path(cancer_type: cancer_type, data_set: data_set, gene_set: gene_set,
                                                            hi_lev_genomic: hi_lev_genomic, clinical_feature: msi_status_row[0]), class:"button" %></td>
  	  	  <td><%= button_to "View miR", show_outcome_path(cancer_type: cancer_type, data_set: data_set, mir_set: mir_set,
                                                            hi_lev_genomic: hi_lev_genomic, clinical_feature: msi_status_row[0]), class:"button" %></td>
  	  	</tr>
  	  </table>
    	
      <%= link_to image_tag("MSI_2.png", height:"150px", alt:"MSI Status chart", title:"MSI Status chart"), 
          get_feature_samples_path(filename:'Y_COADREAD_2013-01-16_CancerGenes_Integrative_MSI-Status.txt') %>
          
      <%= button_to "View Samples", get_feature_samples_path(filename:'Y_COADREAD_2013-01-16_CancerGenes_Integrative_MSI-Status.txt'), class:"button" %>
            
  	</div>
  </td>

</tr>
</table>