config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # analysis_categories
  root :to => 'analysis_categories#select_categories', via: [:get, :post]
  match 'get_feature_samples', to: 'analysis_categories#get_feature_samples', via: [:get, :post]
  match 'feature_samples_sendfile', to: 'analysis_categories#send_feature_samples_file', via: [:get, :post]

  # pages
  match "pages/geneselection", via: 'get'
  match 'gene_selection', to: 'pages#gene_selection', via: [:get, :post]
  match 'gene_selection_sendfile', to: 'pages#send_gene_selection_file', via: [:get, :post]

  match "pages/analysispipeline", to: 'pages#analysispipeline', via: 'get'
  match "pages/datainformation", to: 'pages#datainformation', via: 'get'
  match "pages/projectoverview", to: 'pages#projectoverview', via: 'get'
  match "pages/interpretation", to: 'pages#interpretation', via: 'get'
  match "pages/about", to: 'pages#about', via: 'get'

  match 'send_zip_file', to: 'pages#send_zip_file', via: [:get, :post]

  # high_level_summaries
  match 'show_summary', to: 'high_level_summaries#show_summary_table',  via: :get

  # outcome_summaries
  match 'show_outcome', to: 'outcome_summaries#show_outcome_table',  via: [:get, :post]
  match 'send_file', to: 'outcome_summaries#send_file', via: [:get, :post]
  match 'search_all_outcome_tables', to: 'outcome_summaries#search_outcome_tables', via: [:get, :post]
  match 'search_input_outcome_tables', to: 'outcome_summaries#search_outcome_tables', via: [:get, :post]
  match 'search_genes', to: 'outcome_summaries#search_genes', via: [:get, :post]

end

app/views/pages/about.html.erb
<h1>About Us</h1>

<div class="big-text-box-rounded">
<p>Patrick Flaherty (PF), HoJoon Lee (HJL) and Hanlee P Ji (HPJ) designed the study.</p>
<p>HJL and PF conducted the analysis.</p>
<p>HPJ supervised and coordinated the overall study.</p>

<p>Jennifer Palm and Sue Grimes provided support for the web implementation</p>

<p>This work was supported by the following grants from the NIH: 
	P01HG000205 to PF and HPJ; 
	1U01CA15192001-A1 to HJL and HPJ; 
	1U01CA176299 to HPJ.  
	In addition, HPJ was supported by a Research Scholar Grant, RSG-13-297-01-TBG from the American Cancer Society, 
	the Doris Duke Clinical Foundation, the Wang Family Foundation and the Howard Hughes Medical Foundation.</p>

</div>

app/views/pages/analysispipeline.html.erb
<h1>Analysis Pipeline</h1>

<div style=""><%= image_tag("analysis-pipeline.png", class:"analysis-pipeline", alt:"analysis pipeline") %></div>
<!--
<div class="big-text-box-rounded">
<table class="elastic-net" border="0">
  <tr>
  	<td rowspan="2" style="vertical-align: top">

      <table class="elastic-net-inner">
        <tr>
  	      <td class="box-border">Obtain Tier 3 Data<td>&raquo;</td></span></td>
        </tr>
        <tr>
  	      <td style="height:1px;"><div class="dash">&nbsp;</div></td>
        </tr>
        <tr>
  	      <td class="box-border">Filter Samples<td>&raquo;</td></span></td>
        </tr>
        <tr>
  	      <td style="height:32px;"><div class="dash">&nbsp;</div></td>
        </tr>
        <tr>
  	      <td class="box-border">Integrate genomic data<td>&raquo;</td></span></td>
        </tr>
        <tr>
  	      <td style="padding:0;height:24px;"><div class="dash">&nbsp;</div></td>
        </tr>
        <tr>
  	      <td class="box-border">Filter features & impute missing data<td>&raquo;</td></span></td>
        </tr>
        <tr>
  	      <td style="padding:0;height:24px;"><div class="dash">&nbsp;</div></td>
        </tr>
        <tr>
  	      <td class="box-border">Obtain Clinical Data<td>&raquo;</td></span></td>
        </tr>
        <tr>
  	      <td style="padding:0;height:10px;"><div class="dash">&nbsp;</div></td>
        </tr>
        <tr>
  	      <td class="box-border">Identify genetic markers using regularized regression<td>&raquo;</td></span></td>
        </tr>
      </table>
      
    </td>
  	<th class="round-border">Copy Number</th>
  	<th class="round-border">Mutations</th>
  	<th class="round-border">Methylation</th>
  	<th class="round-border">mRNA-Array</th>
  	<th class="round-border">mRNA-Seq</th>
  </tr>
  <tr>
  	<td colspan="5" style="text-align:right;"><%= image_tag("elastic-net-analysis_868.png", style:"margin-top:0;margin-left:2px", width:"700px", alt:"Elastic-net Analysis", title:"Elastic-net Analysis") %></td>
  </tr>
</table> <!--/table elastic-net -->	

</div> <!-- /big text box -->

app/views/pages/datainformation.html.erb
<h1>Data Information</h1>

<div class="big-text-box-rounded" style="text-align:center;">
  <strong><%= link_to 'DOWNLOAD COADREAD MATRICES', send_zip_file_path(filename: 'Matrix.zip') %> [zip] </strong><br>
  <br>
  <strong>How to read filename:</strong><br>
<%= image_tag("reading_filename.png", alt:"How to read filename", style:"border:1px solid;padding:10px; width:60%;") %>
</div>

app/views/pages/geneselection.html.erb
<h1>Gene Selection</h1>

<% if flash[:notice] -%>
  <div id="notice"><strong><%= flash[:notice] %></strong></div>
<% end -%>
 
<ol>
<li>COSMIC cancer genes: to date, <%= link_to "484 genes", gene_selection_path(filename:'484_CancerGenes.txt') %> were defined as cancer genes according to Catalogue of Somatic Mutations in Cancer (COSMIC).
	The list of genes, cancer_gene_ census.tsv, was downloaded from their website <%= link_to "ftp://ftp.sanger.ac.uk/pub/CGP/cosmic/data_ export/", "ftp://ftp.sanger.ac.uk/pub/CGP/cosmic/data_ export", target:"blank" %></li>
<li><%= link_to "TCGA cancer genes", gene_selection_path(filename:'CancerGenes_COADREAD.txt') %>: we added the list of genes that associated with tumor aggressiveness in TCGA colorectal cancer paper</li>
  <ol style="list-style-type:lower-roman">	
	<li><%= link_to "Significantly mutated genes", gene_selection_path(filename:'Mutation.txt') %>: top 13 mutated genes in hypermutated samples and top 19 mutated genes in non-hypermutated samples from TCGA supplementary table 3</li>
	<li><%= link_to "Copy number changed genes", gene_selection_path(filename:'SCNA.txt') %>: the genes in peak (by supplementary table4) of significant focal amplication/deletion from TCGA supplementary table 11</li>
	<li><%= link_to "Expression signatures", gene_selection_path(filename:'GeneExp.txt') %>: top 30 genes that have expression signature associate with tumor aggressiveness (TCGA Figure 5b)</li>
	<li><%= link_to "Methylation signatures", gene_selection_path(filename:'Methyl.txt') %>: top 344 genes with prove that has the highest compound p values (TCGA supplementary table 11)</li>
  </ol>
<li><%= link_to "20 known target genes", gene_selection_path(filename:'20_MSI_genes.txt') %> for microsatellite Instability: Our supplementary table 1 shows the list of 20 genes including TGFBR2 and ACVR2A.</li>
</ol>

<div style="margin-left:20px; font-weight:bold; font-style: italic;">Collectively 1,085 genes were included in our study.</div>

app/views/pages/geneselection_table.html.erb
<h1>Gene File</h1>
<div style="text-align:center;">
DOWNLOAD: <%= link_to 'CSV', gene_selection_sendfile_path(filename: @filename) %>
</div>

<% theads = @table_array.shift %>
<table class="gene_selection">
  <thead>
  <tr>						
  	<th class="primary_thead" colspan="<%= @table_array[0].length %>"><%= @filename.gsub('_', ' ').gsub('.txt', '')%></th>	
  </tr>
  <tr>
  	<% theads.each do |heading1| %>
  	<th style="padding:2px"><%= heading1 %></th>
  	<% end %>
  </tr>
  </thead>
  <tbody>
  <% @table_array.each do |row| %>
  <tr>
  	<% row.each do |item| %>
    <td><%= item %></td>
    <% end %>
  </tr>
  <% end %>
  </tbody>
</table>

app/views/pages/interpretation.html.erb
<h1>Elastic-net Interpretation</h1>
<div style=""><%= image_tag("interpretation.png", class:"interpretation", alt:"elastic-net interpretation") %></div>
<p>
Each clinical parameter has own unique distribution of genomic signatures (Figure A). 
Copy number alteration features were most common in N status while methylation features were most common in the prediction of 
T status. Mutation was relatively common feature for MSI status compared to other clinical parameters. 
Inverse association is dominant in clinical stage and T status while direct association is dominant in N status and MSI (Figure B).
</p>

app/views/pages/projectoverview.html.erb
<h1>Project Overview</h1>
<div style=""><%= image_tag("overview_crc.png", class:"overview", alt:"project overview") %></div>