config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # analysis_categories
  root :to => 'analysis_categories#select_categories', via: [:get, :post]
  match 'get_feature_samples', to: 'analysis_categories#get_feature_samples', via: [:get, :post]
  match 'feature_samples_sendfile', to: 'analysis_categories#send_feature_samples_file', via: [:get, :post]

  # pages
  match "pages/geneselection", via: 'get'
  match 'gene_selection', to: 'pages#gene_selection', via: [:get, :post]
  match 'gene_selection_sendfile', to: 'pages#send_gene_selection_file', via: [:get, :post]

  match "pages/analysispipeline", to: 'pages#analysispipeline', via: 'get'
  match "pages/datainformation", to: 'pages#datainformation', via: 'get'
  match "pages/projectoverview", to: 'pages#projectoverview', via: 'get'
  match "pages/interpretation", to: 'pages#interpretation', via: 'get'
  match "pages/about", to: 'pages#about', via: 'get'

  match 'send_zip_file', to: 'pages#send_zip_file', via: [:get, :post]

  # high_level_summaries
  match 'show_summary', to: 'high_level_summaries#show_summary_table',  via: :get

  # outcome_summaries
  match 'show_outcome', to: 'outcome_summaries#show_outcome_table',  via: [:get, :post]
  match 'send_file', to: 'outcome_summaries#send_file', via: [:get, :post]
  match 'search_all_outcome_tables', to: 'outcome_summaries#search_outcome_tables', via: [:get, :post]
  match 'search_input_outcome_tables', to: 'outcome_summaries#search_outcome_tables', via: [:get, :post]
  match 'search_genes', to: 'outcome_summaries#search_genes', via: [:get, :post]

end

app/models/outcome_summary.rb
class OutcomeSummary < ApplicationRecord
        
  def self.get_outcome_table(cancer_type, data_set, gene_set, mir_set, genomic, clinical_feature) 
    if !mir_set.blank?
      outcome_file_name = [cancer_type, data_set, mir_set, genomic, clinical_feature].join("_") + ".txt"       
      outcome_file_path = CoadreadTcga::Application::config.data_file_root + [data_set, cancer_type, 'Outcome_Summary_miR', outcome_file_name].join("/") 
    else
      outcome_file_name = [cancer_type, data_set, gene_set, genomic, clinical_feature].join("_") + ".txt"       
      outcome_file_path = CoadreadTcga::Application::config.data_file_root + [data_set, cancer_type, 'Outcome_Summary', outcome_file_name].join("/")             
    end    
    outcome_table_array = ApplicationController.get_table_array(outcome_file_path) if File.exists?(outcome_file_path)    
  end
  
end

app/controllers/outcome_summaries_controller.rb
class OutcomeSummariesController < ApplicationController
  # GET /outcome_summaries
  # GET /outcome_summaries.json
  def index
    #@outcome_summaries = OutcomeSummary.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @outcome_summaries }
    end
  end

  def show_outcome_table
           
    cancer_type = params[:cancer_type]
    data_set = params[:data_set]
    gene_set = params[:gene_set]
    mir_set  = params[:mir_set]
    cosmic_gene_set = params[:cosmic_gene_set]
    genomic = params[:genomic]
    hi_lev_genomic = params[:hi_lev_genomic]
    genomic_for_heading = params[:genomic_for_heading]
    clinical_feature = params[:clinical_feature] 
    
    genomic ||= hi_lev_genomic # eliminate redundancy, in case genomic and hi_lev_genomic are both "Integrative". Get file with _Integrative_ in name (rather than the genomic or IntegrativeGenomic?)
        
    outcome_table_array = OutcomeSummary.get_outcome_table(cancer_type, data_set, gene_set, mir_set, genomic, clinical_feature)
     
    locals = {cancer_type: cancer_type, data_set: data_set, gene_set: gene_set, mir_set: mir_set, genomic: genomic, hi_lev_genomic: hi_lev_genomic, 
              clinical_feature: clinical_feature, genomic_for_heading: genomic_for_heading, outcome_table_array: outcome_table_array}   
    genomic_headers = ''
    if (hi_lev_genomic == "Integrative")
      if params[:mir_set]
        genomic_headers = %w[CopyNumber miR-Seq] 
      else
        genomic_headers = HighLevelSummary.get_genomic_headers(cancer_type, data_set, gene_set, hi_lev_genomic)
      end
      locals = locals.merge({genomic_headers: genomic_headers})
    end

    #if (outcome_table_array.blank? || outcome_table_array.size <= 1) #no file or no data in file
    if outcome_table_array.blank?
      if (hi_lev_genomic == 'Integrative Genomic')
        locals[:hi_lev_genomic] = 'Integrative'
        locals.delete(:genomic) #don't need this param to go back to Integrative Results Summary      
        respond_to do |format|
          format.html { 
            flash[:notice] = "No associated genes were found correlating #{genomic.gsub('Integrative', '')} to #{clinical_feature}"
            #flash[:notice] << " Debug::hi lev genomic=Integrative Genomic, filename=#{[cancer_type, data_set, gene_set, genomic, clinical_feature].join('_')}"
            redirect_to show_outcome_path(locals)
          }
        end # /respond_to        

      elsif ((hi_lev_genomic == 'Integrative') || (hi_lev_genomic == 'Individual'))
        locals = {cancer_type: cancer_type, data_set: data_set, gene_set: gene_set, hi_lev_genomic: hi_lev_genomic}
        respond_to do |format|
          format.html { 
            #flash[:notice] = "No associated genes were found correlating #{genomic} to #{clinical_feature}"
            flash[:notice] = "No associated data was found for #{clinical_feature}"
            #flash[:notice] << " Debug::hi lev genomic=#{hi_lev_genomic}, filename: #{[cancer_type, data_set, gene_set, genomic, clinical_feature].join('_')}"
            #redirect_to show_summary_path(locals)
            redirect_to root_path
          }
        end # /respond_to
          
      end # /if hi_lev_genomic...                
    else
      render 'show_outcome_table', :locals => locals
    end #if outcome_table...
  end #show outcome table
  
  def search_outcome_tables
           
    cancer_type = params[:cancer_type]
    data_set = params[:data_set]
    gene_set = params[:gene_set]
    cosmic_gene_set = params[:cosmic_gene_set]
    genomic = params[:genomic]
    hi_lev_genomic = params[:hi_lev_genomic]
    clinical_feature = params[:clinical_feature] 
                                                            #cancer_type, data_set, gene_set, genomic, clinical_feature
    outcome_table_array_clinicalstage = OutcomeSummary.get_outcome_table('COADREAD', '2013-01-16', 'CancerGenes', '', 'Integrative', 'ClinicalStage')
    @headings = outcome_table_array_clinicalstage.shift
    outcome_table_array_tstatus = OutcomeSummary.get_outcome_table('COADREAD', '2013-01-16', 'CancerGenes', '', 'Integrative', 'T-Status')
    outcome_table_array_tstatus.shift
    outcome_table_array_nstatus = OutcomeSummary.get_outcome_table('COADREAD', '2013-01-16', 'CancerGenes', '', 'Integrative', 'N-Status')
    outcome_table_array_nstatus.shift
    outcome_table_array_msi = OutcomeSummary.get_outcome_table('COADREAD', '2013-01-16', 'CancerGenes', '', 'Integrative', 'MSI-Status')
    outcome_table_array_msi.shift
    
# adding miR outcomes
    outcome_table_array_mir_clinicalstage = OutcomeSummary.get_outcome_table('COADREAD', '2013-01-16', '', 'AllmiR', 'Integrative', 'ClinicalStage')
    @headings = outcome_table_array_mir_clinicalstage.shift
    outcome_table_array_mir_tstatus = OutcomeSummary.get_outcome_table('COADREAD', '2013-01-16', '', 'AllmiR', 'Integrative', 'T-Status')
    outcome_table_array_mir_tstatus.shift
    outcome_table_array_mir_nstatus = OutcomeSummary.get_outcome_table('COADREAD', '2013-01-16', '', 'AllmiR', 'Integrative', 'N-Status')
    outcome_table_array_mir_nstatus.shift
    outcome_table_array_mir_msi = OutcomeSummary.get_outcome_table('COADREAD', '2013-01-16', '', 'AllmiR', 'Integrative', 'MSI-Status')
    outcome_table_array_mir_msi.shift
        
    @outcome_table_all_hash = { #[ "a", "b" ].concat( ["c", "d"] ) #=> [ "a", "b", "c", "d" ] 
      'ClinicalStage' => outcome_table_array_clinicalstage.concat(outcome_table_array_mir_clinicalstage),
      'T-Status' => outcome_table_array_tstatus.concat(outcome_table_array_mir_tstatus),
      'N-Status' => outcome_table_array_nstatus.concat(outcome_table_array_mir_nstatus),
      'MSI-Status' => outcome_table_array_msi.concat(outcome_table_array_mir_msi)        
    }
     
    if params[:input_search]      
      gon.search_input = select_input = get_search_genes_list       
      render 'search_outcome_tables', :locals => {select_input:select_input, data_table_id:'outcome_summary_input'}                   
    else
      render 'search_outcome_tables', :locals => {select_input:'', data_table_id:'outcome_summary_all'} 
    end  
    
  end #search outcome tables
  
  def get_search_genes_list

    genes_select_input = [params[:genesearch][:genes_select]] if !params[:genesearch][:genes_select].blank?
 
    unless params[:genesearch][:genes_text].blank?
      genes_text_input = params[:genesearch][:genes_text].gsub(/[^,\s\w-]/, '') #clean string; leave comma, space, word char, hyphen alone  
      genes_text_input = genes_text_input.split(/[,\s]/)
      genes_text_input.reject! { |g| g.empty? }
    end

    genes_list = []
    if !genes_select_input.blank? && genes_text_input.blank?
      genes_list.concat( genes_select_input ) 
    elsif !genes_text_input.blank? && genes_select_input.blank?
      genes_list.concat( genes_text_input )
    elsif !genes_select_input.blank? && !genes_text_input.blank?
      genes_list.concat(genes_select_input).concat(genes_text_input)
    end
    genes_list.join('|')
  
  end
  
  def get_gene_sample
    render text: "gene: #{params[:gene]}<br />feature: #{params[:clinical_feature]}<br />genomic: #{params[:genomic]}<br />Table load and matrix queries coming next..."
    #gene_list = Gene.where(:name => params[:gene])
    #render 'show_gene', :locals => {gene_list: gene_list}
  end

  def send_file(file_type = params[:file_type], 
                cancer_type = params[:cancer_type], 
                data_set = params[:data_set], 
                gene_set = params[:gene_set], 
                mir_set = params[:mir_set],
                genomic = params[:genomic], 
                clinical_feature = params[:clinical_feature])
    file_name = [cancer_type, data_set, gene_set, genomic, clinical_feature].join("_") + '.csv'
    file_name = [cancer_type, data_set, mir_set, genomic, clinical_feature].join("_") + '.csv' if mir_set
    table_array = OutcomeSummary.get_outcome_table(cancer_type, data_set, gene_set, mir_set, genomic, clinical_feature)
    #render text: table_array
    csv_file = ApplicationController.to_csv(file_name, table_array)
    send_data csv_file, :type => 'text/csv; charset=iso-8859-1; header=present', 
      :disposition => "attachment;filename=#{file_name}"
  end
  
end

app/helpers/outcome_summaries_helper.rb
module OutcomeSummariesHelper
  
  def to_arrow(field)
    if field.to_s.match(/\+/) 
       newfield = field.gsub(/(\+)\Z/,' &uarr;')
    elsif field.to_s.match(/\-/) 
       newfield = field.gsub(/(\-)\Z/,' &darr;')     
    end
  end
end

app/views/outcome_summaries/index.html.erb
<h1>Listing outcome_summaries</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @outcome_summaries.each do |outcome_summary| %>
  <tr>
    <td><%= link_to 'Show', outcome_summary %></td>
    <td><%= link_to 'Edit', edit_outcome_summary_path(outcome_summary) %></td>
    <td><%= link_to 'Destroy', outcome_summary, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Outcome summary', new_outcome_summary_path %>

app/views/outcome_summaries/search_outcome_tables.html.erb
<h1 style="font-size: 1.55em;text-align: center; margin-top:1em;">Search Genes <% unless select_input.blank? %><%= ": #{select_input.gsub('|', ', ')}" %><% end %></h1>
<br>
<% @headings.unshift('Clinical Feature') %>
<% @headings.pop(4) %>
<table class="outcome" id="<%= data_table_id %>">
  <thead>							
  <tr>
  	<%  @headings.each do |heading1| %>
  	<th style="padding:2px"><%= heading1 %></th>
  	<% end %>
  </tr>
  </thead>
  <tbody>
  <% @outcome_table_all_hash.each_pair do |feature, data| %>
    <% data.each do |row| %>  
    <tr>
  	  <td><%= feature %></td>  	              
      <td><%= row[0] %></td>
      <td style="font-style:italic;"><%= row[1] %></td>
      <td><%= row[2] %></td>
      <td><%= row[3] %></td>
      <td><%= raw to_arrow(row[4]) %></td>
      <td><%= raw to_arrow(row[5]) %></td>
      <td style="text-align:center"><%= raw to_arrow(row[6]) %></td>
      <td style="text-align:center"><%= raw to_arrow(row[7]) %></td>
      <td class="break-long-string" style="text-align:left"><%= raw row[8].gsub(',', ',<br>') %></td>
      <td><%= row[9] %></td>
    </tr> 
    <% end %>
  <% end %>
  </tbody>
</table>

 
      

app/views/outcome_summaries/show_outcome_table.html.erb
<div style="display:inline;float:right;text-align:right;">
<% genomic = hi_lev_genomic if hi_lev_genomic == "Integrative" %>
DOWNLOAD: <%= link_to 'CSV', send_file_path(file_type: 'outcome_file', cancer_type:cancer_type, data_set:data_set, 
                                            gene_set:gene_set, mir_set: mir_set, genomic:genomic, clinical_feature:clinical_feature) %>
</div>

<% if genomic_for_heading %>
<h1>Results Summary based on <%= genomic_for_heading %></h1>
<% else %>
<h1>Results Summary based on Integrative Genomics</h1>
<% end %>

<h2 style="margin:0;">Clinical feature: <%= clinical_feature %></h2>

<% if mir_set && outcome_table_array[1].blank? %><div id="notice" style="font-style: italic">No data currently available, Genomic Signature links may provide additional data</div><% end %>
<% if flash[:notice] -%>
  <div id="notice"><strong><%= flash[:notice] %></strong></div>
<% end -%>

<table class="summary-nav">
<tr>

<td>
<div class="genomic-nav">
<% if hi_lev_genomic == 'Integrative' %>
  View Elastic-net Results by Separate Genomic Signature: &nbsp;|&nbsp;
  <% genomic_headers.each do |genomic| %>
    <%= link_to genomic, show_outcome_path(cancer_type: cancer_type, data_set: data_set, gene_set: gene_set, mir_set: mir_set,                                    
                                           hi_lev_genomic: 'Integrative Genomic', genomic: 'Integrative'+genomic, 
                                           genomic_for_heading: genomic, clinical_feature: clinical_feature), 'data-no-turbolink' => true %>&nbsp;|&nbsp;
  <% end %>
<% end %>                                               
</div>
</td>

<td style="text-align:right;">
<% if hi_lev_genomic == 'Integrative Genomic'%>
  <%= link_to 'Back', show_outcome_path(cancer_type: cancer_type, data_set: data_set, gene_set: gene_set, mir_set: mir_set,
                                        hi_lev_genomic: 'Integrative', clinical_feature: clinical_feature), 'data-no-turbolink' => true %> 
<% else %> 
  <%= link_to 'Back', root_path %>                                            
<% end %>
</td>

</tr>
</table>

<% primary_theads = outcome_table_array.shift %>
<% primary_theads.pop(4) %>
<table class="outcome" id="outcome_summary">
  <thead>							
  <tr>
  	<% primary_theads.each do |heading1| %>
  	<th style="padding:2px"><%= heading1 %></th>
  	<% end %>
  </tr>
  </thead>
  <tbody>
  <% outcome_table_array.each do |row| %>
  <tr>
    <td><%= row[0] %></td>
    <td style="font-style:italic;"><%= row[1] %></td>
    <td><%= row[2] %></td>
    <td><%= row[3] %></td>
    <td><%= raw to_arrow(row[4]) %></td>
    <td><%= raw to_arrow(row[5]) %></td>
    <td><%= raw to_arrow(row[6]) %></td>
    <td style="text-align:center"><%= raw to_arrow(row[7]) %></td>
    <td class="break-long-string"><%= raw row[8].gsub(',', ',<br>') %></td>
    <td><%= row[9] %></td>
  </tr>
  <% end %>
  </tbody>
</table>