config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # analysis_categories
  root :to => 'analysis_categories#select_categories', via: [:get, :post]
  match 'get_feature_samples', to: 'analysis_categories#get_feature_samples', via: [:get, :post]
  match 'feature_samples_sendfile', to: 'analysis_categories#send_feature_samples_file', via: [:get, :post]

  # pages
  match "pages/geneselection", via: 'get'
  match 'gene_selection', to: 'pages#gene_selection', via: [:get, :post]
  match 'gene_selection_sendfile', to: 'pages#send_gene_selection_file', via: [:get, :post]

  match "pages/analysispipeline", to: 'pages#analysispipeline', via: 'get'
  match "pages/datainformation", to: 'pages#datainformation', via: 'get'
  match "pages/projectoverview", to: 'pages#projectoverview', via: 'get'
  match "pages/interpretation", to: 'pages#interpretation', via: 'get'
  match "pages/about", to: 'pages#about', via: 'get'

  match 'send_zip_file', to: 'pages#send_zip_file', via: [:get, :post]

  # high_level_summaries
  match 'show_summary', to: 'high_level_summaries#show_summary_table',  via: :get

  # outcome_summaries
  match 'show_outcome', to: 'outcome_summaries#show_outcome_table',  via: [:get, :post]
  match 'send_file', to: 'outcome_summaries#send_file', via: [:get, :post]
  match 'search_all_outcome_tables', to: 'outcome_summaries#search_outcome_tables', via: [:get, :post]
  match 'search_input_outcome_tables', to: 'outcome_summaries#search_outcome_tables', via: [:get, :post]
  match 'search_genes', to: 'outcome_summaries#search_genes', via: [:get, :post]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Cancer Genome Atlas Analysis of Colorectal Cancer - Ji Research Group - Stanford University</title>
  <meta name="description" content=""> 
  <meta charset="utf-8">  
  <meta name="viewport" content="width=device-width"> 
  <meta name="description" content="Compilation of multiple genomic data types (mutations, copy number alterations, 
      	gene expression and methylation status) as well as clinical meta-data from The Cancer Genome Atlas">
  
  <%= include_gon %>
  <%= stylesheet_link_tag "application-all", media: "all" , "data-turbolinks-track" => true%>
  <!--[if IE]>
    <%= stylesheet_link_tag "application-ie", :media => "all" %>
  <![endif]-->
  <!--[if lt IE 8]>
    <style type="text/css">
      .left_logo {padding-bottom:4px !important}
    </style>
  <![endif]-->
  
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Droid+Sans:regular,bold|Source+Sans+Pro:regular,bold">
  <%= csrf_meta_tags %>
  
  <!-- jQuery code to help with :hover on iOS devices -->
  <script type="text/javascript">
    $(document).ready(function () {
        if ((navigator.userAgent.match(/iPhone/i)) || (navigator.userAgent.match(/iPod/i)) || (navigator.userAgent.match(/iPad/i))) {
          $("button").click(function () {});
          $("a").click(function () {});
          $("nav a").click(function () {});
          $("footer table.footer-table td a").click(function () {});
          $("outcome_summaries genomic-nav a").click(function () {});
          $("outcome_summaries a").click(function () {});
          $("outcome_summaries table.outcome tr").click(function () {});
          $("outcome_summaries table.outcome tr").click(function () {});
          $("outcome_summaries table.outcome td.sorting_1").click(function () {}); 
        } 
    });
  </script>
  
</head>
<body class="<%= controller.controller_name %>">
 <script>
 //Make older browsers aware of new HTML5 layout tags
 'header nav aside article footer section figure figcaption'.replace(/\w+/g, function (n) { document.createElement(n) })
 </script>
  <div id="container">
    <header>
      <table class="header_content">
      	<tr>
          <td class="left_logo"><a href="http://stanford.edu" target="_blank"><%= image_tag("SU_seal_white_90.png", height:"90px", alt:"Stanford Seal", title:"Stanford Seal") %></a></td>
          <td class="page_title">Stanford - Cancer Genome Atlas Analysis of Colorectal Cancer</td>
        </tr>
      </table>
    </header> 
    <nav>
      <div class="buttons">
        <div><%= link_to "Elastic-Net Analysis", root_path, class:(request.fullpath == root_path ? "currentpage" : '') %></div>
        <div><%= link_to "Results", pages_interpretation_path, class:(request.fullpath == pages_interpretation_path ? "currentpage" : '') %></div>
        <div><%= link_to "Analysis Pipeline", pages_analysispipeline_path, class:(request.fullpath == pages_analysispipeline_path ? "currentpage" : '') %></div>        
        <div><%= link_to "Gene Selection", pages_geneselection_path, class:(request.fullpath == pages_geneselection_path ? "currentpage" : '') %></div>        
        <div><%= link_to "Data Information", pages_datainformation_path, class:(request.fullpath == pages_datainformation_path ? "currentpage" : '') %></div>
        <div><%= link_to "Project Overview", pages_projectoverview_path, class:(request.fullpath == pages_projectoverview_path ? "currentpage" : '') %></div>
        <div><%= link_to "About", pages_about_path, class:(request.fullpath == pages_about_path ? "currentpage" : '') %></div>
      </div>
    </nav>
    <aside></aside>
    <!-- main content -->
    <article>
      <%= yield %>
    </article><!-- /main content -->
    <footer>
      <table class="footer-table" style="width:100%">
       	<tr>
       	  <td style="text-align:left;">Site by <a href="http://dna-discovery.stanford.edu">Ji Research Group</a><br>
       	  	<a href="mailto:ji-research-web@stanford.edu?subject=tcga_crc website">Contact</a><br>
       	  	&copy; <%= Time.now.year %> Stanford University. All rights reserved.
       	  </td>
       	  <td style="text-align:right;">Funding Provided by:<br>
       	  	<ul class="funding">
       	  	  <li><a href="http://www.nih.gov"><%= image_tag("NIH-logo.gif", alt:"National Institutes of Health", title:"National Institutes of Health") %></a></li>
       	  	  <li><a href="http://www.cancer.gov"><%= image_tag("NCI-logo.png", alt:"National Cancer Institute", title:"National Cancer Institute") %></a></li>
       	  	  <li><a href="http://www.genome.gov"><%= image_tag("NHGRI-logo.gif", alt:"National Human Genome Research Institute", title:"National Human Genome Research Institute") %></a></li>
       	  	  <li><a href="http://www.hhmi.org"><%= image_tag("HHMI-logo.png", alt:"Howard Hughes Medical Institute", title:"National Cancer Institute") %></a></li>       	  	         	  	  
       	  	  <li><a href="http://www.ddcf.org/Medical-Research/Program-Strategies/Clinical-Research/"><%= image_tag("DorisDuke-logo.gif", alt:"Doris Duke Charitable Foundation", title:"Doris Duke Charitable Foundation") %></a></li>
       	    </ul>       	  	
       	  </td>
       	</tr>
      </table>	
    </footer>
  </div><!-- /container -->	
</body>
</html>